name: "Compatibility: Canary Smoke Tests"
on:
  push:
    branches:
      - master
      - release/*

jobs:
  test_on_new_project:
    runs-on: ubuntu-24.04
    name: "${{matrix.project.name}}"
    strategy:
      fail-fast: false
      matrix:
        project:
          # Community projects
          -  name: elixirscript
             repo: https://github.com/elixirscript/elixirscript.git

          -  name: guardian
             repo: https://github.com/ueberauth/guardian.git

          -  name: distillery
             repo: https://github.com/bitwalker/distillery.git

          -  name: timex
             repo: https://github.com/bitwalker/timex.git

          -  name: jason
             repo: https://github.com/michalmuskala/jason.git

          -  name: ex_machina
             repo: https://github.com/thoughtbot/ex_machina.git

          -  name: graphql
             repo: https://github.com/graphql-elixir/graphql.git

          -  name: absinthe
             repo: https://github.com/absinthe-graphql/absinthe.git

          -  name: poison
             repo: https://github.com/devinus/poison.git

          -  name: mox
             repo: https://github.com/dashbitco/mox.git

          -  name: benchee
             repo: https://github.com/PragTob/benchee.git

          -  name: next-ls
             repo: https://github.com/elixir-tools/next-ls.git

          -  name: gen_lsp
             repo: https://github.com/elixir-tools/gen_lsp.git

          -  name: req
             repo: https://github.com/wojtekmach/req.git

          -  name: bandit
             repo: https://github.com/mtrudel/bandit.git

          -  name: decimal
             repo: https://github.com/ericmj/decimal.git

          # Elixir
          -  name: elixir
             repo: https://github.com/elixir-lang/elixir.git

          -  name: ex_doc
             repo: https://github.com/elixir-lang/ex_doc.git

          -  name: flow
             repo: https://github.com/elixir-lang/flow.git

          -  name: gettext
             repo: https://github.com/elixir-lang/gettext.git

          -  name: gen_stage
             repo: https://github.com/elixir-lang/gen_stage.git

          -  name: ecto
             repo: https://github.com/elixir-ecto/ecto.git

          -  name: ecto_sql
             repo: https://github.com/elixir-ecto/ecto_sql.git

          -  name: plug
             repo: https://github.com/elixir-plug/plug.git

          # Phoenix
          -  name: phoenix
             repo: https://github.com/phoenixframework/phoenix.git

          -  name: phoenix_html
             repo: https://github.com/phoenixframework/phoenix_html.git

          -  name: phoenix_pubsub
             repo: https://github.com/phoenixframework/phoenix_pubsub.git

          -  name: phoenix_ecto
             repo: https://github.com/phoenixframework/phoenix_ecto.git

          -  name: phoenix_live_reload
             repo: https://github.com/phoenixframework/phoenix_live_reload.git

          # Nerves
          -  name: nerves
             repo: https://github.com/nerves-project/nerves.git

          # Nx
          -  name: nx
             repo: https://github.com/elixir-nx/nx.git

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2
          elixir-version: 1.17.3
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: bash test/run_on_project.sh ${{matrix.project.repo}} ${{matrix.project.name}}
