name: "Housekeeping"
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  format:
    name: "used mix format"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.3
          elixir-version: 1.19.4
      - run: mix deps.get
      - run: mix compile
      - run: ./test/check_formatted.sh

  trigger:
    name: "tested that for each check there is at least one trigger assertion"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.3
          elixir-version: 1.19.4
      - run: mix deps.get
      - run: mix test test/credo/check/housekeeping_trigger.exs

  params:
    name: "tested that for each check all params are covered by tests"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.3
          elixir-version: 1.19.4
      - run: mix deps.get
      - run: mix test test/credo/check/housekeeping_params.exs

  assert_triggers:
    name: "all triggers are looked up and confirmed"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.3
          elixir-version: 1.19.4
      - run: mix deps.get
      - run: ASSERT_TRIGGERS=1 mix test

  no_deps_compiler_warnings:
    name: "compiling deps shows no compiler warnings (optional)"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.3
          elixir-version: 1.19.4
      - run: mix deps.get
      - run: mix deps.compile 2>&1 | ./test/error_if_warnings.sh
